#!/usr/bin/env python
from __future__ import print_function
import sys
from optparse import OptionParser
from os.path import dirname, basename, join, splitext, isfile

from ngs_utils.bed_utils import verify_bed
from ngs_utils.file_utils import adjust_path, safe_mkdir, verify_file
from ngs_utils.logger import critical

from venn import venn


def main():
    parser = OptionParser(usage='Usage: ' + basename(__file__) + ' bed_or_vcf bed_or_vcf ... -o results_dir')
    parser.add_option('-o', '--output-dir', dest='output_dir')
    (opts, args) = parser.parse_args(sys.argv[1:])

    input_fpaths = [verify_file(fpath) for fpath in args]
    names_map = dict()
    
    ''' Example VCFs:
    input_fpaths = tuple([join(vcfs_dirpath, vcf_name) for vcf_name in [
        'syn3-vardict.vcf.gz',
        'syn3-ensemble.vcf.gz',
        'syn3-tumor-single-vardict.vcf.gz',
        'syn3-truth.vcf.gz',
    ]])
    names_map = {
        'syn3-vardict.vcf.gz': 'vardict-paired',
        'syn3-ensemble.vcf.gz': 'ensemble-paired',
        'syn3-tumor-single-vardict.vcf.gz': 'vardict-single',
        'syn3-truth.vcf.gz': 'truth-paired'}
    '''

    '''Example BED files:    
    bed_fpaths = tuple([join(beds_dirpath, bed) for bed in [
        'AZ.bed',
        'CRE.bed',
        'IDT.bed',
        'Med.bed',
        # 'One.bed',
        # 'One.hg38tohg19.bed',
        'V6.bed',
    ]])
    names_map = {
        'AZ': 'AZ Exome',
        'CRE': 'B',
        'V6': 'A',
        'IDT': 'D',
        'Med': 'C'}
    '''

    if not opts.__dict__.get('output_dir'):
        critical('Please, provide output dir with -o')
    output_dir = adjust_path(opts.output_dir)
    safe_mkdir(output_dir)
    work_dirpath = safe_mkdir(join(output_dir, 'intersections'))

    intersection_size_by_subset = venn.run(work_dirpath, input_fpaths)

    json_txt = venn.save_venn_diagram_data(intersection_size_by_subset, names_map)

    html_file = venn.write_html(output_dir, json_txt, input_fpaths)

    print('-----------------------')
    print('')
    print('HTML: ' + html_file)


if __name__ == '__main__':
    main()


